DATASET:
  root_dataset: "./data/"
  list_train: "./data/training.odgt"
  list_val: "./data/validation.odgt"
  num_class: 2
  imgSizes: (300, 375, 450, 525, 600)
  imgMaxSize: 1000
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True

MODEL:
  arch_encoder: "mobilenetv2dilated"
  arch_decoder: "c1_deepsup"
  fc_dim: 320

TRAIN:
  batch_size_per_gpu: 3
  num_epoch: 2000
  start_epoch: 699
  epoch_iters: 1000
  optim: "SGD"
  lr_encoder: 0.00001
  lr_decoder: 0.00001
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-10
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: True
  checkpoint: "epoch_480.pth"

TEST:
  checkpoint: "epoch_480.pth"
  result: "./GUI/" 

DIR: "ckpt/ade20k-mobilenetv2dilated-c1_deepsup_fnf_best/"
